### ISSUE TITLE
export 변수+=값 이 동작하지 않습니다

### ISSUE THREAD

**Issue by jhj9109** [42-shell/minishell#14]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/36416495/175897791-0d5f2b28-f267-49b5-87a1-f11ed36a2cdd.png">

**Comment by jhj9109** [comment]
팬이에요

**Comment by codeyoma** [comment]
bash의 assignment operator를 인지하고, export에서도 지원하는 것을 알고있었지만, 내부 논의로 추가하진 않았습니다. 이참에 넣어야 겠군요!

**Comment by 16EB** [comment]
다음 커밋에서 지원될 예정입니다.

**Comment by 16EB** [comment]
resolve on e1af67575e5f248fdfb9e0d60006e945a2d85679
