### ISSUE TITLE
export 변수명 오동작

### ISSUE THREAD

**Issue by jhj9109** [42-shell/minishell#15]
export 변수명
의 동작이, 해당 이름의 지역변수를 환경변수로 설정해주는것으로 알고 있는데,

저희는 지역변수를 가지고 있지 않으니, 변수명 유효성만 체크하고 넘어가면 되는데
다음과같은 기대치 않은 오류가 발생하네요.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/36416495/175907423-77471e8e-ecb3-40fe-814d-9699e32ad056.png">

**Comment by jhj9109** [comment]
env 키=밸류 형식 아니여도 되나요? .....

**Comment by jhj9109** [comment]
env 키=밸류 아니여도 오류는 안 나는거군요?

export에서는 키만 있는 아이들도 출력되고
env에서는 키=밸류형식만 출력되네요

<img width="368" alt="image" src="https://user-images.githubusercontent.com/36416495/175954412-7c56e5b7-e9b8-4a32-8573-12faa168e093.png">

**Comment by 16EB** [comment]
값이 없는 변수를 execve할 때 envp로 내보내는 오류는 유효한듯 합니다. 다음 커밋에 해결될 예정입니다.

**Comment by 16EB** [comment]
fix on e1af67575e5f248fdfb9e0d60006e945a2d85679
