### ISSUE TITLE
echo $invalid_var_name 동작에 대한 의문

### ISSUE THREAD

**Issue by jhj9109** [42-shell/minishell#16]
<img width="1889" alt="image" src="https://user-images.githubusercontent.com/36416495/176391558-819b8de6-0252-4515-ae66-07b28f798496.png">
builtin 함수들의 동작을 분석하는 과정에서
$다음에 바로 var 규칙에 어긋나는 변수명이 오는과정에서 어떤 결과가 일어날지 보고있는데

bash에서는 첫글자를 가져가버립니다. zsh도 달라보이지만, 지역변수의 경우 zsh에서는 첫글자로 numeric을 허용해서 정상적인 변수명으로 인식해서 나온 결과입니다.

그것과 비교했을때, 바로뒤에 잘못된 변수명이 들어왔을때의 동작이, 타당해 보이지 않습니다.

어떤 상황에서 특이한 동작이 나올때마다, 이건 구현하셨나....? 하며 살피는 중입니다. ㅎㅎ
(구현하셨으면, 참고도 좀 하고... ㅎ)

**Comment by 16EB** [comment]
해당 사항은 정상이 맞습니다. bash에서의 $1은 첫번째 인자, $@는 인자로 이루어진 배열을 뜻합니다. 따라서 위의 bash에 입력하신 명령어의 경우에는 $1과 $@가 각각 정상적으로 확장되고 뒤따르는 단어가 연결된 것으로 이해됩니다. 그러나 미니셸에서는 $?를 제외한 특수한 변수을 처리할 필요가 없습니다. 그래서 위 입력과 같은 경우에 $까지만 해석되어 $라는 단어 자체로 연결되고, 그 뒤에 따라오는 단어들이 추가로 연결되도록 의도하였습니다.

**Comment by jhj9109** [comment]
배워갑니다!
